Repository WMass/WRemnants, pull requests merged in 2023-11, with the labels that each got.

#339 fixing bug in propagateToHelicityOption
  scripts/histmakers/w_z_gen_dists.py
  wremnants/syst_tools.py
Labels: bugfix

#338 Add theory agnostic analysis with POI as NOI to CI
  .github/workflows/main.yml
  scripts/combine/setupCombine.py
  utilities/styles/styles.py
  wremnants/combine_theory_helper.py
Labels: enhancement

#347 Fix MiNNLO scale variations
  wremnants/combine_theory_helper.py
  wremnants/theory_corrections.py
Labels: bugfix, high priority

#348 bugfixes to theory agnostic OOA
  scripts/combine/setupCombine.py
  wremnants/CardTool.py
  wremnants/datasets/dataset_tools.py
Labels: enhancement, bugfix, high priority

#352 Fix application of PDF correction
  wremnants/correctionsTensor_helper.py
  wremnants/theory_corrections.py
Labels: bugfix
